version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - OAUTH_SERVER_URL=tu_valor_aqui
      - NODE_ENV=production
      - JWT_SECRET="mi_clave_secreta_jijijaja_escubitrakatelas_cdlatam_123!"
      - DATABASE_URL="file:/app/data/gestion.db"
  nginx:
    image: nginx:latest
    container_name: webserver_nginx_3002
    ports:
      - "3002:3002"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web
    restart: always
