CREATE TABLE `actas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`noActa` varchar(50),
	`atencion` varchar(255),
	`fecha` timestamp,
	`razonSocial` varchar(255),
	`nombreFantasia` varchar(255),
	`rucDniRut` varchar(50),
	`direccionComercial` text,
	`representanteLegal` varchar(255),
	`representanteDni` varchar(50),
	`representanteEmail` varchar(320),
	`representanteFono` varchar(50),
	`contactoTecnico` varchar(255),
	`contactoTecnicoEmail` varchar(320),
	`contactoTecnicoFono` varchar(50),
	`contactoFacturacion` varchar(255),
	`contactoFacturacionEmail` varchar(320),
	`contactoFacturacionFono` varchar(50),
	`serviciosContratados` json,
	`formasPagoImplementacion` json,
	`formasPagoMantencion` json,
	`status` enum('borrador','completado','exportado') NOT NULL DEFAULT 'borrador',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `actas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `evaluaciones` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`actaId` int,
	`unidadNegocios` varchar(100),
	`empresa` varchar(255),
	`solucion` varchar(100),
	`tipoMoneda` varchar(20),
	`montoProyecto` decimal(15,2),
	`tipoCambio` decimal(10,4),
	`totalClp` decimal(15,2),
	`descripcion` text,
	`preventa` varchar(255),
	`fechaEntrega` timestamp,
	`ejecutivoComercial` varchar(255),
	`plazoImplementacion` varchar(50),
	`propuestaNumero` varchar(50),
	`paisImplementacion` varchar(100),
	`rut` varchar(50),
	`nombreCliente` varchar(255),
	`hardware` json,
	`materiales` json,
	`rrhh` json,
	`otrosGastos` json,
	`totalHardware` decimal(15,2),
	`totalMateriales` decimal(15,2),
	`totalRrhh` decimal(15,2),
	`totalOtros` decimal(15,2),
	`totalGastos` decimal(15,2),
	`status` enum('borrador','completado','exportado') NOT NULL DEFAULT 'borrador',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evaluaciones_id` PRIMARY KEY(`id`)
);
