-- Seed de descripciones para catalog_implementacion_items
-- Generado desde nro_acta_000001(20).pdf

UPDATE catalog_implementacion_items SET descripcion = 'Gestión centralizada de canales de televisión en vivo, permitiendo la organización de grillas de programación y configuraciones de transmisión en tiempo real.' WHERE `key` = 'admin_contenido_lineal';
UPDATE catalog_implementacion_items SET descripcion = 'Configuración y empaquetamiento flexible de canales premium, permitiendo crear ofertas personalizadas y control de acceso bajo suscripción.' WHERE `key` = 'admin_paquetes_tv_premium';
UPDATE catalog_implementacion_items SET descripcion = 'Sistema de seguridad que permite restringir el acceso a contenidos específicos mediante contraseñas o PIN, garantizando un entorno seguro para el hogar.' WHERE `key` = 'control_parental';
UPDATE catalog_implementacion_items SET descripcion = 'Módulo integral para la gestión de perfiles de clientes, altas, bajas, asignación de dispositivos y control de sesiones activas.' WHERE `key` = 'admin_usuarios';
UPDATE catalog_implementacion_items SET descripcion = 'Aplicación optimizada nativamente para dispositivos Set-Top Box basados en Android, garantizando estabilidad y rendimiento.' WHERE `key` = 'app_deco_stb_android';
UPDATE catalog_implementacion_items SET descripcion = 'Soporte y compatibilidad con decodificadores basados en sistemas Linux para despliegues personalizados de infraestructura de hardware.' WHERE `key` = 'integracion_deco_stb_linux';
UPDATE catalog_implementacion_items SET descripcion = 'Interfaz diseñada exclusivamente para pantallas grandes bajo el ecosistema Android TV, compatible con control remoto estándar.' WHERE `key` = 'app_android_smart_tv';
UPDATE catalog_implementacion_items SET descripcion = 'Desarrollo compatible con el sistema operativo webOS de LG, cumpliendo con los estándares de rendimiento de la tienda oficial.' WHERE `key` = 'app_tv_lg';
UPDATE catalog_implementacion_items SET descripcion = 'Aplicación optimizada para el sistema operativo Tizen de Samsung, asegurando una experiencia fluida y alta fidelidad visual.' WHERE `key` = 'app_tv_samsung';
UPDATE catalog_implementacion_items SET descripcion = 'Diseño responsivo y versátil enfocado en movilidad, optimizado para el consumo eficiente de datos y streaming en smartphones.' WHERE `key` = 'app_telefonos_android';
UPDATE catalog_implementacion_items SET descripcion = 'Versión nativa desarrollada para iOS, cumpliendo con las pautas estéticas de Apple y soporte para transmisiones seguras.' WHERE `key` = 'app_telefonos_iphone';
UPDATE catalog_implementacion_items SET descripcion = 'Cliente de escritorio dedicado para sistemas operativos de Microsoft que maximiza el uso del hardware local para la decodificación de flujos de video de alta tasa de bits.' WHERE `key` = 'app_windows';
UPDATE catalog_implementacion_items SET descripcion = 'Software optimizado para macOS, aprovechando las capacidades gráficas y de rendimiento del hardware de Apple para garantizar una reproducción fluida.' WHERE `key` = 'app_mac';
UPDATE catalog_implementacion_items SET descripcion = 'Visualización interactiva en pantalla de los horarios de programas, metadatos, sinopsis y programación futura de los canales.' WHERE `key` = 'epg';
UPDATE catalog_implementacion_items SET descripcion = 'Panel analítico que recopila métricas de consumo de los usuarios, canales más vistos, tiempos de permanencia y rendimiento de red.' WHERE `key` = 'reportes_sistema_estadisticas';
UPDATE catalog_implementacion_items SET descripcion = 'Arquitectura de distribución de contenido que conmuta entre múltiples proveedores de CDN para optimizar la latencia y disponibilidad mundial.' WHERE `key` = 'solucion_multi_cdn';
UPDATE catalog_implementacion_items SET descripcion = 'Diseño y estructuración de la cabecera técnica para la correcta recepción, procesamiento y retransmisión de las señales de video.' WHERE `key` = 'ingenieria_red_head_end';
UPDATE catalog_implementacion_items SET descripcion = 'Capacidad de segmentación del sistema para operar de manera independiente o centralizada bajo entornos sedes u oficinas.' WHERE `key` = 'sucursal';
UPDATE catalog_implementacion_items SET descripcion = 'Disponibilidad de APIs y conectores para enlazar la plataforma con pasarelas de pago, CRMs, ERPs y sistemas externos de facturación.' WHERE `key` = 'integracion_otros_sistemas';
UPDATE catalog_implementacion_items SET descripcion = 'Espacio web donde el usuario final puede administrar sus suscripciones, actualizar sus métodos de pago y visualizar su historial.' WHERE `key` = 'portal_autogestion';
UPDATE catalog_implementacion_items SET descripcion = 'Estructura comercial jerárquica que permite la creación y coexistencia de planes de servicio con diferentes capacidades y precios.' WHERE `key` = 'multiplan';
UPDATE catalog_implementacion_items SET descripcion = 'Mecanismo de seguridad geográfica o de red que limita el acceso al contenido únicamente a rangos de direcciones IP autorizados.' WHERE `key` = 'restriccion_ip';
UPDATE catalog_implementacion_items SET descripcion = 'Páginas de destino configurables de manera dinámica para operar bajo esquemas de marca blanca y múltiples operadores en paralelo.' WHERE `key` = 'landing_multiempresas';
UPDATE catalog_implementacion_items SET descripcion = 'Sistema de respaldo automático que conmuta la transmisión a un flujo alternativo de inmediato ante cualquier caída de la señal principal.' WHERE `key` = 'fail_over_streaming';
UPDATE catalog_implementacion_items SET descripcion = 'Mecanismo de alta disponibilidad en la nube que conmuta automáticamente entre proveedores de infraestructura de red ante degradaciones de tráfico para evitar interrupciones.' WHERE `key` = 'fail_over_cdn_cloud';
UPDATE catalog_implementacion_items SET descripcion = 'Plataforma de procesamiento y virtualización de canales directamente en la nube, permitiendo la ingesta, transcodificación y empaquetado sin dependencia de hardware local.' WHERE `key` = 'channel_cloud';
UPDATE catalog_implementacion_items SET descripcion = 'Módulo de gestión de derechos digitales (DRM) y control de autenticación de credenciales para asegurar la visualización autorizada de activos multimedia protegidos.' WHERE `key` = 'acceso_contenido';
UPDATE catalog_implementacion_items SET descripcion = 'Protocolo robusto de transporte de flujos de video profesionales (como SRT o Zixi) desde la cabecera principal hasta los nodos periféricos de distribución.' WHERE `key` = 'transporte_cabecera';
